(defun esperantize-region (start end)
  (interactive (list (region-beginning) (region-end)))
  (let ((contents (buffer-substring start end)))
    (dolist (subst '(("CX" . "Ĉ")
                    ("Cx" . "Ĉ")
                    ("GX" . "Ĝ")
                    ("Gx" . "Ĝ")
                    ("JX" . "Ĵ")
                    ("Jx" . "Ĵ")
                    ("SX" . "Ŝ")
                    ("Sx" . "Ŝ")
                    ("UX" . "Ŭ")
                    ("Ux" . "Ŭ")
                    ("cx" . "ĉ")
                    ("gx" . "ĝ")
                    ("jx" . "ĵ")
                    ("sx" . "ŝ")
                    ("ux" . "ŭ")))
      (setq contents (string-replace (car subst) (cdr subst) contents)))
    (replace-region-contents start end contents)))
